### ISSUE TITLE
New ADB action: restart ADB

### ISSUE THREAD

**Issue by danikula** [pbreault/adb-idea#11]
Sometimes ADB stucks, so I have to execute command `adb kill-server; adb-start-server` to restart it. Please, add this command to actions list.

Thanks so much for your plugin!

**Comment by emakovsky** [comment]
The issue was opened 1 year and it's still open.
Is it a complicated feature to implement?

**Comment by pbreault** [comment]
Closing this as it is more than 2 years old. I never got around to implementing this. 
ADB got a lot more stable during this period so it's not applicable anymore.
