### ISSUE TITLE
Incompatible with Andorid Studio 4.2.2 

### ISSUE THREAD

**Issue by RomanShtyk** [pbreault/adb-idea#134]
Android Studio 4.2.2
Build #AI-202.7660.26.42.7486908, built on June 24, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 24
Registry: external.system.auto.import.disabled=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=206
Non-Bundled Plugins: com.bloc.intellij_generator_plugin, dev.polek.adbwifi, wu.seal.tool.jsontokotlin, org.jetbrains.kotlin, com.retail.sorter
------------
10:56 AM	Plugin Error
					Plugin "ADB Idea" is incompatible (since build 203.7717 > AI-202.7660.26).

![image](https://user-images.githubusercontent.com/25960348/130924423-f0383006-7375-4be7-9ca6-c96686f261d2.png)

**Comment by RomanShtyk** [comment]
@pbreault It was already installed and Android Studio automatically upgraded to 4.2.2

**Comment by pbreault** [comment]
> @pbreault It was already installed and Android Studio automatically upgraded to 4.2.2

Awesome :)
