### ISSUE TITLE
No device found error

### ISSUE THREAD

**Issue by emakovsky** [pbreault/adb-idea#14]
I use android studio 1.1.0

The plugin works fine in one of my projects. But when I switch to the other one and try to invoke any command from the plugin I see an error "No device found".
The device is actually available and visible in e.g. android ddms.

I tried to reinstall the plugin but it doesn't help.
What can be wrong and how to debug the problem?

**Comment by pbreault** [comment]
Does the second project works correctly if you open it first? Or does the plugin never ever works with this project?

And can you see anything different in this project? Like is it an android auto/tv/wear project? What version of the gradle plugin are you using, etc.

And when you say android ddms, you mean the "Android" panel in android studio or do you mean that you started Android Device Monitor (formerly known as ddms) ?

Thanks!

**Comment by emakovsky** [comment]
The plugin never works with this particular project.
It uses gradle version 1.1.3 and it's a usual android project like others.

I named ddms a panel in android studio because it has a title "android ddms".
Actually it doesn't matter. The device is available and I see the logs.

Is that possible to see some logs or other info which can help to find where is the problem?

**Comment by pbreault** [comment]
That's an interesting bug.

There is

**Comment by pbreault** [comment]
That's an interesting bug.
Sadly there is no log for this, in case of an error it will display the error message and that's pretty much it.

Looking at the code, the things that might cause this would be if it can't find/parse the package name.
Are you modifying the package name dynamically in your build.gradle?

Is your project available somewhere so that I can check this out? Or maybe a version with pretty much everything stripped out that still shows the bug?

**Comment by trinitron01** [comment]
I have got the same problem, basically it doesn't work in a project that was imported from eclipse and it has a slightly different folder structure than a typical project that was created from scratch in Android Studio.

**Comment by pbreault** [comment]
Which version of Gradle and Android Studio are you using?

Any chance that you can send me a sample project using the same Gradle file and structure so that I can repro and fix it?

**Comment by trinitron01** [comment]
Android Studio 1.2.2

com.android.tools.build:gradle:1.2.3
compileSdkVersion 22
buildToolsVersion "22.0.1"

Unfortunately I can't send you any samples. However apart from being imported from eclipse I actually don't see any significant differences that could affect it in any way. It's a Project with single android application module.
