### ISSUE TITLE
Bug (v1.6.11): for a project with multiple modules, it always asks on which to perform any operation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [pbreault/adb-idea#162]
On a project that has multiple modules, yet it has only one that can be launched anyway, it always asks on which module to perform an operation, whether it to uninstall, kill, or clear-data.

Please fix this. I didn't have this issue before.

Here's how it looks like:

![image](https://github.com/pbreault/adb-idea/assets/5357526/d8f99c52-c01a-4a45-819e-bcd81b9912a1)

This occurs on both stable and canary versions:

stable:

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.github.drjacky.avocado (1.0.0)
    Show As ... (1.1.1)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.marketplace (231.9392.3)
    String Manipulation (9.12.0)
    GenerateSerialVersionUID (3.0.3)
    idea.plugin.protoeditor (231.9225.5)
    com.steve.plugins.autoscroll (1.1)
    com.dethlex.numberconverter (1.5.0)
    izhangzhihao.rainbow.brackets (2023.3.7)
    com.ppismerov.ksvu (0.0.1)
    net.aquadc.mike.plugin (0.30)
    com.developerphil.adbidea (1.6.11)
    GenerateSerializationHelpers (1.0.6)

canary:

Android Studio Iguana | 2023.2.1 Canary 17
Build #AI-232.10227.8.2321.11191411, built on December 7, 2023
Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 12
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    Show As ... (1.1.1)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.marketplace (232.10227.13)
    String Manipulation (9.12.0)
    GenerateSerialVersionUID (3.0.3)
    idea.plugin.protoeditor (232.9559.10)
    com.steve.plugins.autoscroll (1.1)
    com.dethlex.numberconverter (1.5.0)
    izhangzhihao.rainbow.brackets (2023.3.7)
    com.ppismerov.ksvu (0.0.1)
    net.aquadc.mike.plugin (0.30)
    com.developerphil.adbidea (1.6.13)
    GenerateSerializationHelpers (1.0.6)

**Comment by AndroidDeveloperLB** [comment]
How odd. Now that I test the same project on stable version of the IDE, I don't see this issue.

Android Studio Hedgehog | 2023.1.1
Build #AI-231.9392.1.2311.11076708, built on November 9, 2023
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 12
Registry:
    external.system.auto.import.disabled=true
    debugger.watches.in.variables=false
    ide.text.editor.with.preview.show.floating.toolbar=false

Non-Bundled Plugins:
    com.github.drjacky.avocado (1.0.0)
    Show As ... (1.1.1)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.marketplace (231.9392.3)
    String Manipulation (9.12.0)
    GenerateSerialVersionUID (3.0.3)
    idea.plugin.protoeditor (231.9225.5)
    com.steve.plugins.autoscroll (1.1)
    com.dethlex.numberconverter (2.0.0)
    izhangzhihao.rainbow.brackets (2023.3.7)
    com.ppismerov.ksvu (0.0.1)
    net.aquadc.mike.plugin (0.30)
    com.developerphil.adbidea (1.6.11)
    GenerateSerializationHelpers (1.0.6)

**Comment by MenosGrante** [comment]
Occurs to me as well on Android Studio Iguana | 2023.2.1 Beta 1, however I don't remember this on the Canary versions of the same Android Studio versions.

**Comment by AndroidDeveloperLB** [comment]
@MenosGrante Do you know of any workaround, other than use a different version of the IDE ?
Also, are you saying it doesn't occur for you on Canary, but occurs on stable?

**Comment by mccartneym** [comment]
I'm seeing the same problem on Iguana. Would be great to get this fixed.

**Comment by pbreault** [comment]
Fixed in the latest version. Good catch!

**Comment by AndroidDeveloperLB** [comment]
I think it also has an issue with multiple devices/emulators recently : nothing is offered, as if nothing is connected. 
Was it also fixed?

**Comment by pbreault** [comment]
> I think it also has an issue with multiple devices/emulators recently : nothing is offered, as if nothing is connected. Was it also fixed?
> 
> EDIT: Seems fixed too.

Yes, that's fixed on JellyFish.

**Comment by AndroidDeveloperLB** [comment]
Nice
