### ISSUE TITLE
Adb connect

### ISSUE THREAD

**Issue by andrey-shikhov** [pbreault/adb-idea#17]
It will be great if here was a possibility to use connect/disconnect commands.

I every day in studio console go to platform-tools and type ./adb connect 192.168.1.xxx to attach my phone via adb wireless so it will be cool to do with one key shortcut

**Comment by pbreault** [comment]
This is outside of the scope of this plugin.
Since the time this issue has been created, this plugin has been released which fullfills this goal: https://github.com/pedrovgs/AndroidWiFiADB
