### ISSUE TITLE
Start / restart issues when using AndroidManifest merger

### ISSUE THREAD

**Issue by gbourassa** [pbreault/adb-idea#18]
I have a case where my AndroidManifest.xml in main is empty, and my actual manifest(s) are in "flavor" folders. This is where my launch activity is declared.

When executing ADB IDEA start (or restart), I get the following error:

ADB IDEA
com.mypackage.name could not bet started on XXX.  
ADB Output: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.mypackage.name/null } Error type 3 Error: Activity class {com.mypackage.name/null} does not exist.

It doesn't seem to be able to resolve the launch activity name.

**Comment by pbreault** [comment]
Hey @gbourassa,
I have reproduced the bug and I think that I have a working fix.
Can you download [this snapshot version](https://www.dropbox.com/s/r46qefdswrbpsa8/adb_idea-1.1.4.jar?dl=0) and confirm that it is working now?

**Comment by gbourassa** [comment]
Yes, I confirm that this version fixes my issue!

Thanks a lot for the awesome reactivity!

**Comment by pbreault** [comment]
Fixed in 1.2.0
