### ISSUE TITLE
Android Studio 1.4:Action Start & Restart can't work

### ISSUE THREAD

**Issue by X3Daniel** [pbreault/adb-idea#23]

**Comment by pbreault** [comment]
I can reproduce it on my end. A fix is on its way.

**Comment by pbreault** [comment]
@X3Daniel I just pushed a 1.2.1 version that fixes this. You can install it by clicking on "check for updates" in studio or by installing the jar manually from [here](https://github.com/pbreault/adb-idea/releases/tag/1.2.1) .

Is it working for you now?

**Comment by X3Daniel** [comment]
上午10:10:21 ReflectException: java.lang.NoSuchMethodException: org.jetbrains.android.run.DeviceChooser.(java.lang.Boolean, com.intellij.openapi.ui.DialogWrapper$OkAction, org.jetbrains.android.facet.AndroidFacet, com.developerphil.adbidea.ui.DeviceChooserDialog$2) (show balloon)

my AndroidStudio Version is 1.4 Beta3 . 
it seems all of ADB Action can't working in this version

**Comment by cypressious** [comment]
This only happens if you have more than one device running.

**Comment by pbreault** [comment]
Version 1.2.2 has been pushed, it fixes the problem above, let me know if you have any other issue.
