### ISSUE TITLE
Cannot start or restart app

### ISSUE THREAD

**Issue by Android-s14** [pbreault/adb-idea#28]
So I've got a pretty complex project structure (multiple modules, manifests, and flavours), and I assume this may be confusing the plugin, because when I try to select `start` or `restart` it returns:

```
ADB IDEA: <applicationId> could not bet started on asus-nexus_7-06d8b524. 

ADB Output: 
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=<applicationId>/null }
Error type 3
Error: Activity class {<applicationId>/null} does not exist.
```

ApplicationId is recognized correctly, so all other commands work fine, it's only the main activity that cannot be correctly identified.

**Comment by Android-s14** [comment]
One more detail is that the default activity is not in the "main" manifest fail, it comes from one of the flavour manifests. Perhaps, this is the reason for it not being recognized. Would be great for the plugin to be able to take the default activity from the currently selected flavour, or as a fallback to show a dialog to select the default activity to launch.

**Comment by pbreault** [comment]
Old issue and cannot be reproduced. Closing for now.
