### ISSUE TITLE
No device in chooser when multiple USB devices are connected with AS 1.5 (stable)

### ISSUE THREAD

**Issue by nmDejamobile** [pbreault/adb-idea#31]
Hi,

When I have multiple devices connected (a Nexus 5X and a Samsung GS5) using USB, the window to choose the device is empty and so no action (delete app, reset app, ...) are possible.
If I unplug all devices except one, the device chooser logically don't appear and the action works.

Thanks.

**Comment by hekbobo** [comment]
I also encountered

**Comment by maksim88** [comment]
Also encountered the issue with **multiple** devices connected (AS 1.5 stable):
(and plugin version 1.2.3 where NoSuchMethodError should be fixed)
`
NoSuchMethodError: com.android.tools.idea.run.LaunchCompatibility.canRunOnDevice(Lcom/android/sdklib/AndroidVersion;Lcom/android/sdklib/IAndroidTarget;Ljava/util/EnumSet;Lcom/android/ddmlib/IDevice;Lcom/android/sdklib/IAndroidTarget;)Lcom/android/tools/idea/run/LaunchCompatibility;
14:50:18 ADB IDEA: No Device found
`

**Comment by tspaulding0222** [comment]
Same here

    com.android.tools.idea.run.LaunchCompatibility.canRunOnDevice(Lcom/android/sdklib/AndroidVersion;Lcom/android/sdklib/IAndroidTarget;Ljava/util/EnumSet;Lcom/android/ddmlib/IDevice;Lcom/android/sdklib/IAndroidTarget;)Lcom/android/tools/idea/run/LaunchCompatibility;

**Comment by pbreault** [comment]
Hi, this should be fixed in version 1.2.4.
Thanks
