### ISSUE TITLE
Suggestion: Close ballons using keyboard shortcut

### ISSUE THREAD

**Issue by cutiko** [pbreault/adb-idea#36]
Greetings

Thanks for the great plugin Im working with an app that store local data so when I have to test something speed up the deleting process. Very usefull, thank you so much.

Can you please add a shortcut for closing the ballons. This way we can get a visual confirmation about the executed task, but also an quick and simpl way to close them,

Thanks,

**Comment by pbreault** [comment]
Not applicable anymore in 1.3.0 as the balloons only show up in case of errors
