### ISSUE TITLE
No devices found and Error thrown

### ISSUE THREAD

**Issue by Danm72** [pbreault/adb-idea#37]
Android Studio 2.0 Preview 9
Build #AI-143.2571730, built on January 29, 2016
JRE: 1.6.0_65-b14-468-11M4833 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple Inc.

Two Emulators and one device connected.

12:04:12 PM ReflectException: java.lang.NoSuchMethodException: No similar method canRunOnDevice with params [class com.android.sdklib.AndroidVersion, class com.android.sdklib.repositoryv2.targets.PlatformTarget, class java.util.RegularEnumSet, class com.android.ddmlib.Device, class org.joor.Reflect$NULL] could be found on type class com.android.tools.idea.run.LaunchCompatibility.

**Comment by pbreault** [comment]
Hey @Danm72 !
I can reproduced the issue. I will take a look over the weekend.
Thanks.

**Comment by pbreault** [comment]
Bug fixed in 1.2.6 that was released today.
Thanks for reporting it!
