### ISSUE TITLE
Compatibility with instant run

### ISSUE THREAD

**Issue by fmatosqg** [pbreault/adb-idea#47]
Since Android Studio 2.0 and instant run, app start/restart won't play nice with instant run. Commands will use the apk initially build, when the correct action would be to rely on AS cold start function.

**Comment by pbreault** [comment]
Good catch, let me see what we can do to make it work.

**Comment by fmatosqg** [comment]
I tried hard debugging AS to find the right place to add that call but couldn't get anywhere close to it. Do you have any hints on how to find that kind of information? The only thing that occurs to me is asking on AS emailing lists.

**Comment by pbreault** [comment]
I haven't checked yet. Looks like you are doing exactly what I am doing: running studio, using breakpoints and looking at the source. I'll take a stab at it tomorrow.

**Comment by pbreault** [comment]
Looks like this is working now in the most recent versions of studio.
Closing.
