### ISSUE TITLE
About Intellij Plugin

### ISSUE THREAD

**Issue by HongnianZhang** [pbreault/adb-idea#56]
Hi,I try to write a plugin to use adb push ,But I can not get the "adb" command.
I read your code , find you use the `AndroidSdkUtils.getAndroidSdkPathsFromExistingPlatforms()`,but I can not import `AndroidSdkUtils` 
Could you tell me why? Please.
(sorry for my English)

**Comment by pbreault** [comment]
I'm a bit late to the party here. sorry about that.

if you checkout the latest version in `master`, you should be able to import the project as a gradle project in Intellij 2016.3 or in 2017.1 eap.

After that, you need to update your gradle.properties to point to a valid installation of android studio. take a look at `gradle.properties.change_me` for the properties that are required.

After that, you will be able to build the project using the `buildPlugin` and  the `runIdea` gradle tasks.

I'm closing this issue but I'll reopen it if needed. Let me know if it works for you.
