### ISSUE TITLE
ADB Idea with AS 2.4 preview 1

### ISSUE THREAD

**Issue by mtrakal** [pbreault/adb-idea#61]
`ADB IDEA: No Device found`

Never found any device

**Comment by ckesc** [comment]
May be it's related to https://github.com/pbreault/adb-idea/issues/59

**Comment by pbreault** [comment]
I can reproduce it on my end. I'm working on a fix

**Comment by pbreault** [comment]
Fixed in 1.4.1

**Comment by mtrakal** [comment]
Wow, thank you, it's working 👍  . You are best! 🥇
