### ISSUE TITLE
Clear Permissions Command

### ISSUE THREAD

**Issue by yigitserin** [pbreault/adb-idea#78]
Hey there, 

I created a command that is very similar to clear data command. Is is to clear app permissions of app. Can you implement this ?

Here is the code:

https://gist.github.com/yigitserin/6f21731b8d02a7f2753476c471c43de5

**Comment by EarlOfEgo** [comment]
Hey, 
I already did this and it is merged, see #70

**Comment by yigitserin** [comment]
Nice!
