### ISSUE TITLE
Fail to start while syncing

### ISSUE THREAD

**Issue by ckesc** [pbreault/adb-idea#79]
I called `Clear and restart` while AndroidStudio was performing gradle sync. And got:
```
ADB IDEA: Start fail... Parameter specified as non-null is null: method com.developerphil.adbidea.adb.ShellCommandsFactory.startActivity, parameter activityName
```

Maybe plugin should check if sync is going and print more relevant text :)

**Comment by pbreault** [comment]
That was a great idea. It's implemented in 1.5.0. Thanks for the suggestion!
