### ISSUE TITLE
Multiple devices in Android Studio 3.4 canary 3

### ISSUE THREAD

**Issue by svob** [pbreault/adb-idea#99]
Plugin doesn't work in AS 3.4 cnary 3 when multiple devices are connected. 
Dialog is empty and `16:50	ADB IDEA: No Device found` message appears in event log

**Comment by Pitel** [comment]
Same with 3.5 canary

**Comment by pbreault** [comment]
Thanks for reporting. I'll have the fix in 1.5.3 tomorrow.

**Comment by pbreault** [comment]
Fixed in 1.5.3
